# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: home
    url: '#about'
    weight: 10
  - name: publications
    url: 'publication/'
    weight: 12
  - name: posts
    url: 'post/'
    weight: 20
  - name: "code for pubs"
    url: 'code/'
    weight: 30
  - name: teaching
    url: 'teaching/'
    weight: 40
  - name: "R packages"
    url: 'rpackages/'
    weight: 50
  - name: projects
    url: '#projects'
    weight: 60
  - name: contact
    url: '#contact'
    weight: 70
